#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while IFS=: read file
do
	echo "$file" | cut -d ":" -f 1,3,6
done < /etc/passwd
